version: '3'
services:
  splitgraph:
    image: splitgraph/engine:${DOCKER_TAG-stable}
    environment:
      - POSTGRES_USER=sgr
      - POSTGRES_PASSWORD=supersecure
      - POSTGRES_DB=splitgraph
      - SG_LOGLEVEL=INFO

      # Credentials for Matomo, edit these if needed
      - MATOMO_HOST=matomo
      - MATOMO_PORT=3306
      - MATOMO_USER=matomo
      - MATOMO_PASS=matomo

      # Host/port for Elasticsearch
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    ports:
      - 5432:5432
    volumes:
      - ./.sgconfig:/.sgconfig
      - ./mounting:/mounting
      # Store Splitgraph metadata in a volume
      - splitgraph_metadata:/var/lib/postgresql/data
      - splitgraph_data:/var/lib/splitgraph/objects

volumes:
  splitgraph_metadata:
  splitgraph_data:
