[tool.poetry]
name = "splitgraph"
version = "0.0.0"
description = "Splitgraph command line library and Python client"
authors = ["Splitgraph Limited"]
readme = "README.md"
homepage = "https://www.splitgraph.com"
repository = "https://github.com/splitgraph/splitgraph"

[tool.poetry.dependencies]
python = ">=3.5"
click = "^7"
psycopg2-binary = "^2"
parsimonious = "^0.8"
minio = "^4"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
pyfakefs = "^3.5"
pytest-cov = "^2.6"
pytest-env = "^0.6"
coveralls = "^1.5"

[tool.poetry.scripts]
sgr = 'splitgraph.commandline:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"